# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-07-19 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('commodity_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='商品ID')),
                ('commodityname', models.CharField(max_length=20, verbose_name='商品名稱')),
                ('category', models.CharField(max_length=20, verbose_name='商品分類')),
                ('price', models.IntegerField(verbose_name='商品價格')),
                ('quantity', models.IntegerField(verbose_name='商品數量')),
                ('c_content', models.TextField(max_length=100, verbose_name='商品說明')),
                ('c_photo', models.ImageField(null=True, upload_to='photo/')),
            ],
            options={
                'db_table': 'commodity',
            },
        ),
    ]
