# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-07-24 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodity', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('car_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='購物車ID')),
                ('num', models.IntegerField(verbose_name='數量')),
                ('c_status', models.IntegerField(verbose_name='購物車狀態')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.Commodity')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
            options={
                'db_table': 'shoppingcart',
            },
        ),
    ]
