# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-07-19 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='用戶ID')),
                ('username', models.CharField(max_length=12, verbose_name='用戶名')),
                ('email', models.EmailField(max_length=250, verbose_name='信箱')),
                ('password', models.CharField(max_length=32, verbose_name='密碼')),
                ('phone', models.CharField(max_length=11, verbose_name='電話')),
                ('address', models.CharField(max_length=50, null=True, verbose_name='地址')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
